### ISSUE TITLE
right click opens file

### ISSUE THREAD

**Issue by MarkCate** [SideBarEnhancements-org/SideBarEnhancements#398]
SideBarEnhancements on my new Mac Pro running Mojave 10.14.1 is demonstrating an obstructive or unusual coding behavior. This behavior has been vaguely communicated and even more vaguely dismissed: read carefully. Without SideBarEnhancements, sidebar right click provides normal display of context menu, **without** opening the file object that is right clicked. SideBarEnhancements enhances the right click context menu. However, with SideBarEnhancements installed, **right click opens the clicked file object**! In all operating systems that I am aware of, right click should only open the _file list context menu_. Context menu typically includes an Open command. SideBarEnhancements contains Open commands in its context menu. Rude file opening is really unwelcome here. Is there a way to disable right-click file-open behavior? Say by editing SideBarEnhancements after extracting it with PackageResourceViewer? Or is this obstructive behavior unexpected, a behavior the developer will remove? Or is this behavior intended?

**Comment by titoBouzout** [comment]
This package does not do what you are describing. You most likely seeing https://github.com/SublimeTextIssues/Core/issues/2 that has nothing to do with this package. 

I agree that opening a file in 1 click is rude, the total purpose of it is to save 1 click at cost of being a mayor annoyance.

You can disable this thing by going to Preferences - Settings - User and then add  preview_on_right_click: false which should disable "previewing" the file when you click/right click. 

Basically the same thing is happening when you click a tab, you lose your "sidebar selection" because a new tab was focused so sublime text will go to that file, select it on sidebar trashing your current sidebar selection.

Basically, the same thing is basically happening when you click a folder in sidebar it will open the folder and trash your selection of files so what you have selected it will vanish.

All this stuff to save 1 click, I understand it could have sound like a good idea on paper, but on the practice this is not saving any clicks and is doing more harm than good, to rescue you need to reclick a lot and think what you click again. Go figure.

I use sublime text all day everyday and Im very tired of this 1 click nonsense. I don't want to lose my sidebar selection anymore.

**Comment by MarkCate** [comment]
Yo Tito,
We do then observe bugs in Apple’s new Broadcom chip? Screenshots to Apple engineers. Thanks for your speedy reply.
No, not Core#2, since no right click problems on Mac with ST3, until install your app package. Maybe you have solved a problem for Sublime Text 2 right click?
Wado, Mark
