### ISSUE TITLE
Feature Request: Can Closing Views also Close the Folder

### ISSUE THREAD

**Issue by sundarv85** [SideBarEnhancements-org/SideBarEnhancements#400]
It is possible to also close the folder when "Close Views" action is performed. In issue #384 it is noted that it is not possible. Is that case also applicable when I right the folder and say Close Views? 

The use case is, when I close views, all the open files are closed. Usually I do this so that I can concentrate on the next folder. If that folder is also closed/minimized, it will be one less action :)

**Comment by titoBouzout** [comment]
If you right clicking the folder it may be possible to focus sidebar the send arrow left command. IDK if that will work, will have to try

**Comment by titoBouzout** [comment]
I figured how to send the "left arrow character", but is a bit buggy. 
Implemented it here https://github.com/SideBarEnhancements-org/SideBarEnhancements/commit/2883735e20f96e77787be460c8b11a3ccbd22787 

As the sidebar has an automatic "select the focused view" (which I hate with so much passion) we need to:
- figure out if the folder you just clicked will remain selected when you click close (because if your current focused file is outside of the folder, then the folder you clicked is not selected in sidebar after it lose focus because of the "automatic select my current view" after you close any view of the folder, heck)
- so, focus sidebar
- focus first view to close
- collapse folders
- close all views

This has the downside that if the folder is already collapsed it will uncollapse it....... 

I tried to be sure that the folder is always uncollpased before collapsing it but the tree animation makes it to ignore my code ... attempts with set timeout will also fail because the view with focus after every view is closed is completely unrelated to the folder you click, again because of the automatic file focus.
